#!/usr/bin/with-contenv bash

# make folders
mkdir -p /run/apache2

# configure apache
sed -i 's/User apache/User abc/g' /etc/apache2/httpd.conf
sed -i 's/Group apache/Group abc/g' /etc/apache2/httpd.conf

# permissions
chown abc:abc /config /data
